// MSXgl | Raw files definitions generated by the Build tool

#define PSG_MENU_VGM_SEG 	60
#define PSG_MENU_VGM_REL 	0x0000
#define PSG_MENU_VGM_ABS 	0xF0000
#define PSG_MENU_VGM_SIZE	0x15B2

#define PSG_MATCH_VGM_SEG 	61
#define PSG_MATCH_VGM_REL 	0x0000
#define PSG_MATCH_VGM_ABS 	0xF4000
#define PSG_MATCH_VGM_SIZE	0x15B2
